/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package randomize;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;

/**
 *
 * @author Ben
 */
public class OldMainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    
    public File extFile;
    public String filesDir;
        
    public OldMainWindow() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pathNameField = new javax.swing.JTextField();
        randomButton = new javax.swing.JButton();
        deRandomButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        extensionsMenuOption = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));
        setForeground(java.awt.Color.cyan);
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Directory of Randomness");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 40, 200, 22);

        jLabel2.setText("Path:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 30, 14);

        pathNameField.setText("C:\\Users\\Ben\\Documents\\RandomTest\\Java");
        getContentPane().add(pathNameField);
        pathNameField.setBounds(70, 90, 260, 20);

        randomButton.setText("Randomize!");
        randomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomButtonActionPerformed(evt);
            }
        });
        getContentPane().add(randomButton);
        randomButton.setBounds(50, 180, 110, 23);

        deRandomButton.setText("deRandomize!");
        deRandomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deRandomButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deRandomButton);
        deRandomButton.setBounds(203, 180, 120, 23);

        jMenu1.setText("File");

        extensionsMenuOption.setText("Extensions");
        extensionsMenuOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extensionsMenuOptionActionPerformed(evt);
            }
        });
        jMenu1.add(extensionsMenuOption);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void randomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomButtonActionPerformed
        // TODO add your handling code here:
       // filesDir = this.pathNameField.getText();
        File[] files = new File(filesDir).listFiles();
        System.out.println(files);
        randomize(files, filesDir);
    }//GEN-LAST:event_randomButtonActionPerformed

    private void deRandomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deRandomButtonActionPerformed
        // TODO add your handling code here:
       // filesDir = this.pathNameField.getText();
        File[] files = new File(filesDir).listFiles();
        System.out.println(files);
        deRandomize(files, filesDir);
    }//GEN-LAST:event_deRandomButtonActionPerformed

    private void extensionsMenuOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extensionsMenuOptionActionPerformed
        // TODO add your handling code here:
        //MainWindow mw = new OldMainWindow();
        MainWindow ew = new MainWindow();
        ew.setVisible(true);
    }//GEN-LAST:event_extensionsMenuOptionActionPerformed

    /**
     * @param args the command line arguments
     * 
     * Adds a random 4-digit number to the beginning of every file name.
     */
    public static void randomize(File[] files, String filesDir){
        ArrayList<String> extensions = new ArrayList<String>();
        
        try{
            BufferedReader br = new BufferedReader(new FileReader(filesDir + "\\randomExt.txt"));
            System.out.println(br);
            
            
                String line;
                while ((line = br.readLine()) != null) {

                    if (line.charAt(0) == '.'){
                        extensions.add(line);
                        System.out.println("Line added: " + line);
                        //extensions[arrayLength] = line;
                    }

            }
            br.close();
            
            }catch(Exception e){
                System.out.println("Error reading extensions file: " + e);
        } 
        
        
        for (String extension : extensions){
            for (File f : files){  
                String fileName = f.getName();
                if (fileName.contains(extension)){
                    String oldName = f.getName();
                    char specialChar = oldName.charAt(4);
                    if (specialChar == ')'){
                        oldName = oldName.substring(5);
                    }
                    int randNum = (int)(Math.random() * (9999 - 1000) + 1000);
                    String randString = Integer.toString(randNum);
                    System.out.println(f);
                    String newName = (randString + ")" + oldName);

                    // File (or directory) with new name
                    try{
                        File newFile = new File(filesDir, newName);
                        boolean success = f.renameTo(newFile);
                        System.out.println(newFile);
                        if (!success) {
                            System.out.println("Randomization unsuccessful");

                        }
                        else {
                            f.renameTo(newFile);
                            System.out.println("Renamed to: " + newFile);

                        }
                    } catch (Exception e){
                        System.out.println("Error: File exists.\n" + e );
                    }
                    }
            }
            
            // Rename file (or directory)
            
        // File was not successfully renamed
    }
        } //end of Randomize method
    
    public static void deRandomize(File[] files, String filesDir){
        for (File f : files){
            String fileName = f.getName();
            char specialChar;
            String newName;
            specialChar = fileName.charAt(4);
            if (specialChar == ')'){
                newName = fileName.substring(5);
            }
            else{
                newName = fileName;
            }
            try{
                File newFile = new File(filesDir, newName);
                boolean success = f.renameTo(newFile);
                System.out.println(newFile);
                if (!success) {
                    System.out.println("Randomization unsuccessful");
                    
                }
                else {
                    f.renameTo(newFile);
                    System.out.println("Renamed to: " + newFile);
                    
                }
            } catch (Exception e){
                System.out.println("Error: File exists.\n" + e );
            }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OldMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OldMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OldMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OldMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OldMainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deRandomButton;
    private javax.swing.JMenuItem extensionsMenuOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField pathNameField;
    private javax.swing.JButton randomButton;
    // End of variables declaration//GEN-END:variables
}
